import { ContentItem } from "@/stores/contentStore";
import { StatusBadge } from "@/components/StatusBadge";
import {
  FileText,
  Youtube,
  Twitter,
  Link as LinkIcon,
  MoreHorizontal,
  ExternalLink,
  Copy,
  Trash2,
} from "lucide-react";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { Button } from "@/components/ui/button";
import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
} from "@/components/ui/tooltip";
import { toast } from "sonner";
import { apiFetch } from "@/lib/api";
import { useContentStore } from "@/stores/contentStore";
import { useState } from "react";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";

const typeIcons: Record<string, { icon: typeof FileText; className: string }> =
  {
    article: { icon: FileText, className: "text-muted-foreground" },
    youtube: { icon: Youtube, className: "text-status-failed" },
    twitter: { icon: Twitter, className: "text-status-scraped" },
    unknown: { icon: LinkIcon, className: "text-muted-foreground" },
  };

function getDomain(url: string) {
  try {
    return new URL(url).hostname.replace("www.", "");
  } catch {
    return url;
  }
}

interface ContentCardProps {
  item: ContentItem;
  onClick: () => void;
  style?: React.CSSProperties;
}

export function ContentCard({ item, onClick, style }: ContentCardProps) {
  const [showDelete, setShowDelete] = useState(false);
  const removeItem = useContentStore((s) => s.removeItem);
  const TypeIcon = typeIcons[item.contentType]?.icon || LinkIcon;
  const iconClass =
    typeIcons[item.contentType]?.className || "text-muted-foreground";

  const handleDelete = async () => {
    try {
      await apiFetch(`/api/v1/content/${item._id}`, { method: "DELETE" });
      removeItem(item._id);
      toast.success("Content deleted");
    } catch (err: any) {
      toast.error(err.message || "Failed to delete");
    }
    setShowDelete(false);
  };

  return (
    <>
      <div
        className="group bg-card border border-border rounded-lg p-4 cursor-pointer transition-all duration-200 hover:border-primary/50 animate-fade-in-up"
        onClick={onClick}
        style={style}
      >
        <div className="flex items-start justify-between gap-2 mb-3">
          <div className="flex items-center gap-2">
            <TypeIcon className={`w-4 h-4 shrink-0 ${iconClass}`} />
            <StatusBadge status={item.status} />
            {(item.scrapeBlocked || item.scrapedSuccessfully === false) && (
              <Tooltip>
                <TooltipTrigger asChild>
                  <span className="inline-flex items-center px-2 py-0.5 rounded-full text-[10px] font-medium bg-status-scraping/20 text-status-scraping border border-status-scraping/30">
                    AI summary
                  </span>
                </TooltipTrigger>
                <TooltipContent>
                  Site blocked scraping — summary generated by AI from title
                </TooltipContent>
              </Tooltip>
            )}
          </div>
          <DropdownMenu>
            <DropdownMenuTrigger asChild onClick={(e) => e.stopPropagation()}>
              <Button
                variant="ghost"
                size="icon"
                className="h-7 w-7 opacity-0 group-hover:opacity-100 transition-opacity"
              >
                <MoreHorizontal className="w-4 h-4" />
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent
              align="end"
              onClick={(e) => e.stopPropagation()}
            >
              <DropdownMenuItem
                onClick={() => window.open(item.link, "_blank")}
              >
                <ExternalLink className="w-4 h-4 mr-2" /> Open URL
              </DropdownMenuItem>
              <DropdownMenuItem
                onClick={() => {
                  navigator.clipboard.writeText(item.link);
                  toast.success("Link copied");
                }}
              >
                <Copy className="w-4 h-4 mr-2" /> Copy link
              </DropdownMenuItem>
              <DropdownMenuItem
                className="text-destructive"
                onClick={() => setShowDelete(true)}
              >
                <Trash2 className="w-4 h-4 mr-2" /> Delete
              </DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
        </div>
        <h3 className="font-semibold text-sm leading-snug line-clamp-2 mb-2">
          {item.title || "Untitled"}
        </h3>
        {item.status === "enriched" && item.summary && (
          <p className="text-muted-foreground text-xs leading-relaxed line-clamp-3 mb-3">
            {item.summary}
          </p>
        )}
        {item.tags?.length > 0 && (
          <div className="flex flex-wrap gap-1.5 mb-3">
            {item.tags.slice(0, 3).map((tag) => (
              <span
                key={tag.name}
                className="text-xs bg-secondary px-2 py-0.5 rounded-md text-muted-foreground"
              >
                {tag.name}
              </span>
            ))}
            {item.tags.length > 3 && (
              <span className="text-xs text-text-tertiary">
                +{item.tags.length - 3}
              </span>
            )}
          </div>
        )}
        <div className="flex items-center gap-2 text-xs text-text-tertiary font-mono">
          <LinkIcon className="w-3 h-3" />
          <span className="truncate">{getDomain(item.link)}</span>
          <span className="ml-auto">
            {new Date(item.createdAt).toLocaleDateString("en-GB", {
              day: "numeric",
              month: "short",
              year: "numeric",
            })}
          </span>
        </div>
      </div>

      <AlertDialog open={showDelete} onOpenChange={setShowDelete}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Delete content?</AlertDialogTitle>
            <AlertDialogDescription>
              This action cannot be undone.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Cancel</AlertDialogCancel>
            <AlertDialogAction
              onClick={handleDelete}
              className="bg-destructive text-destructive-foreground hover:bg-destructive/90"
            >
              Delete
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </>
  );
}
